<h4> NOTE </h4> 
All queries which don't have results (such as Q7 and Q9 in PT schema) should has 0 instead of "N/A" in the log files

<h3> Create rank table for storage formats </h3>

1. Copy the results from the tables with title "RESULTS FOR STORAGE FORMATS COMPARISON" into the "results.xlsx" excel file
2. For PT schema, delete values which are 0 (Q7 and Q9)
2. Run the code, and ranking results are saved on "rankings.xlsx" excel file
3. Copy the rankings from "rankings.xlsx" into the according table in "Rank tables" excel file.

In [90]:
import scipy.stats as ss
import pandas as pd
import numpy as np

df = pd.read_excel("C:\\Users\\Sadiq\\Desktop\\results.xlsx", header = None)
print("Original data \n", df, "\n")


df_ranks = []
for index, row in df.iterrows():
    df_ranks.append(ss.rankdata(row))

df_ranks = pd.DataFrame(df_ranks)
# print("Ranks \n", df_ranks, "\n")

df_transpose = df_ranks.transpose()
# print("Transposed Ranks \n", df_transpose, "\n")

rank_table = []
for index, row in df_transpose.iterrows():
    
    result_row = np.zeros(5)  
    for i in range(len(row)):
        result_row[int(row[i])-1] +=1
    rank_table.append(result_row)
    
rank_table = pd.DataFrame(rank_table)
print("Rank Table \n", rank_table)

rank_table.to_excel("C:\\Users\\Sadiq\\Desktop\\rankings.xlsx")

<h3> Compute ranking scores for Storage formats </h3>

1. Run code to calculate Rank Scores for the results which are created after the "Create rank table for storage formats".
2. According to the formula, t is 5, b is 11 ( b is 9 for PT schema)
3. Take the results and copy into the according table in "Rank Scores" excel file

In [91]:
import pandas as pd

df = pd.read_excel("C:\\Users\\Sadiq\\Desktop\\rankings.xlsx", header = None)
df = df.drop(0)
df = df.drop(0, axis = 1)
print("Rank Table \n", df.head(), "\n")

b=9
# b=11         #total number of queries
t=5          #number of file formats
             #r is a rank number 1<=r<=t

df_list = ["avro", "csv", "orc", "parq.", "hive"]
print("Rank Scores \n")

for index, row in df.iterrows():
    s = 0
    for r in range(t):  
        s = s + ( row[r+1]*(t-(r+1)) / (b*(t-1)) )
       
    print(df_list[index-1], "\t", s)

<h3> Create rank table for Partitioning techniques </h3>

1. Copy the results from the tables with title "RESULTS FOR PARTITIONING TECHNIQUES COMPARISON" into the "results.xlsx" excel file
2. Delete values which are 0 (for example Q7 and Q9 in PT schema)
2. Run the code, and results are saved on "rankings.xlsx" excel file
3. Copy the rankings from "rankings.xlsx" into the according table in "Rank tables" excel file.

In [193]:
import scipy.stats as ss
import pandas as pd
import numpy as np

df = pd.read_excel("C:\\Users\\Sadiq\\Desktop\\results.xlsx", header = None)
print("Original data \n", df, "\n")

df_ranks = []
for index, row in df.iterrows():
    df_ranks.append(ss.rankdata(row))

df_ranks = pd.DataFrame(df_ranks)
# print("Ranks \n", df_ranks, "\n")

df_transpose = df_ranks.transpose()
# print("Transposed Ranks \n", df_transpose, "\n")

rank_table = []
for index, row in df_transpose.iterrows():
    
    result_row = np.zeros(3)  
    for i in range(len(row)):
        result_row[int(row[i])-1] +=1
    rank_table.append(result_row)
    
rank_table = pd.DataFrame(rank_table)
print("Rank Table \n", rank_table)

rank_table.to_excel("C:\\Users\\Sadiq\\Desktop\\rankings.xlsx")

<h3> Compute ranking scores for Partitioning Techniques </h3>

1. Run code to calculate Rank Scores for the results which are created after the "Create rank table for partitioning techniques".
2. According to the formula, t is 3, b is 11 (b is 9 for PT)
3. Take the results and copy into the according table in "Rank Scores" excel file

In [192]:
import pandas as pd

df = pd.read_excel("C:\\Users\\Sadiq\\Desktop\\rankings.xlsx", header = None)
df = df.drop(0)
df = df.drop(0, axis = 1)
print("Rank Table \n", df.head(), "\n")

# b=9
b=11         #total number benchmark execurions
t=3          #number of file formats
             #r is a rank number 1<=r<=t
    
df_list = ["HP", "SBP", "PBP" ]
print("Rank Scores \n")

for index, row in df.iterrows():
    s = 0
    for r in range(t):  
        s = s + ( row[r+1]*(t-(r+1)) / (b*(t-1)) )
        
    print(df_list[index-1], "\t", s)

<h3> Create rank table for relational schemas </h3>

1. Copy the results from the tables with title "RESULTS FOR Relational Schema COMPARISON" into the "results.xlsx" excel file
2. Delete values which are 0 (for example Q7 and Q9 in PT schema)
2. Run the code, and results are saved on "rankings.xlsx" excel file
3. Copy the rankings from "rankings.xlsx" into the according table in "Rank tables" excel file.

In [292]:
import scipy.stats as ss
import pandas as pd
import numpy as np

df = pd.read_excel("C:\\Users\\Sadiq\\Desktop\\results.xlsx", header = None)
print("Original data \n", df, "\n")

df_ranks = []
for index, row in df.iterrows():
    df_ranks.append(ss.rankdata(row))

df_ranks = pd.DataFrame(df_ranks)
# print("Ranks \n", df_ranks, "\n")

df_transpose = df_ranks.transpose()
# print("Transposed Ranks \n", df_transpose, "\n")

rank_table = []
for index, row in df_transpose.iterrows():
    
    result_row = np.zeros(3)
    for i in range(len(row)):
        result_row[int(row[i])-1] +=1
    rank_table.append(result_row)
    
rank_table = pd.DataFrame(rank_table)
print("Rank Table \n", rank_table, "\n")


# print("Rank Table Modified \n", rank_table)    
rank_table.to_excel("C:\\Users\\Sadiq\\Desktop\\rankings.xlsx")

<h3> Compute ranking scores for Relational Schemas </h3>

1. Run code to calculate Rank Scores for the results which are created after the "Create rank table for Relational Schemas".
2. According to the formula, t is 3, b is 11 
3. Take the results and copy into the according table in "Rank Scores" excel file

In [291]:
import pandas as pd

df = pd.read_excel("C:\\Users\\Sadiq\\Desktop\\rankings.xlsx", header = None)
df = df.drop(0)
df = df.drop(0, axis = 1)
print("Rank Table \n", df.head(), "\n")

b=11         #total number of queries
t=3          #number of schemas
             #r is a rank number 1<=r<=t

df_list = ["ST", "VT", "PT"]
print("Rank Scores \n")
for index, row in df.iterrows():    
    
    s = 0
    for r in range(t):
        s = s + ( row[r+1]*(t-(r+1)) / (b*(t-1)) )
        
    print(df_list[index-1], "\t", s)

<h3> Create rank table for configurations </h3>

In [297]:
import scipy.stats as ss
import pandas as pd
import numpy as np

df = pd.read_excel("C:\\Users\\Sadiq\\Desktop\\results.xlsx", header = None)
print("Original data \n", df, "\n")

df_ranks = []
for index, row in df.iterrows():
    df_ranks.append(ss.rankdata(row))

df_ranks = pd.DataFrame(df_ranks)
print("Ranks \n", df_ranks, "\n")

df_transpose = df_ranks.transpose()
df_transpose[6][30:] = 31
df_transpose[8][30:] = 31
print("Transposed Ranks \n", df_transpose, "\n")

rank_table = []
for index, row in df_transpose.iterrows():
    
    result_row = np.zeros(45)  
    for i in range(len(row)):
        result_row[int(row[i])-1] +=1
    rank_table.append(result_row)
    
rank_table = pd.DataFrame(rank_table)
rank_table[30][30:] = rank_table[30][30:] - 2
print("Rank Table \n", rank_table)

rank_table.to_excel("C:\\Users\\Sadiq\\Desktop\\rankings.xlsx")

Original data
         0       1       2       3       4       5       6       7       8   \
0    34.93   49.61   27.28   24.96   28.04   32.73   49.16   25.18   23.63
1    79.98  168.67   58.01   57.74   58.53   74.62  164.27   49.55   52.79
2    12.21   32.02    6.50    6.94    6.52   10.78   30.89    5.26    6.50
3   175.17  232.85  171.15  169.99  167.32  176.80  224.43  163.97  168.21
4    44.46   93.88   32.49   33.47   31.06   43.52   92.66   29.43   32.36
5    52.11   98.34   43.34   47.17   41.15   46.94   97.66   38.46   40.04
6    94.45  146.52   72.47   74.26   76.62   78.33  135.02   66.31   71.83
7   130.90  172.25  127.25  131.65  125.40  129.03  169.17  119.32  125.43
8    41.51   71.97   31.66   33.86   32.89   39.91   67.08   28.58   29.79
9    10.19   28.63    2.44    4.25    2.43    9.72   28.74    1.82    2.25
10    5.35   14.29    1.40    1.68    1.86    5.47   14.05    1.35    2.12

        9   ...      59      60      61      62      63      64      65  \
0    26.14  ...   33.63   12.66   28.46   19.04   35.01   81.71   67.59
1    52.87  ...  102.00  133.40   99.50   96.96  118.16  155.06  201.66
2     6.50  ...    6.53   13.78    4.45    4.28    4.64   21.01   45.40
3   165.21  ...  543.16  667.36  660.72  627.41  651.41  634.76  731.85
4    28.89  ...   52.42   71.33   47.97   48.35   48.60   75.25   85.51
5    40.85  ...   41.90   56.25   34.22   38.74   36.46   98.48  131.07
6    64.84  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN
7   125.52  ...   54.11   66.54   52.07   53.82   55.82   49.07   67.03
8    29.63  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN
9     2.27  ...   30.01   37.62   26.08   26.42   26.17   97.40  104.32
10    1.68  ...   11.60   17.10    9.56    9.61    9.26   54.25   65.88

        66      67      68
0   109.33   96.74  110.55
1   152.54  162.95  187.69
2    31.95   43.57   50.27
3   676.68  631.05  753.91
4    80.24   96.07  100.10
5    99.61  119.89  124.03
6      NaN     NaN     NaN
7    47.20   45.50   47.82
8      NaN     NaN     NaN
9    91.22  107.09  106.25
10   56.20   73.67   81.79

[11 rows x 69 columns]

Ranks
       0     1     2     3     4     5     6     7     8     9   ...    59  \
0   42.0  56.0  26.0  22.0  29.0  35.0  55.0  23.0  21.0  24.0  ...  37.0
1   27.0  62.0  15.0  14.0  16.0  22.0  61.0  10.0  12.0  13.0  ...  43.0
2   38.0  61.0  20.0  26.0  23.5  37.0  58.0  13.0  20.0  20.0  ...  25.0
3    7.0  21.0   6.0   5.0   3.0   8.0  18.0   1.0   4.0   2.0  ...  26.0
4   20.0  62.0  12.0  13.0  10.0  19.0  61.0   7.0  11.0   4.0  ...  37.0
5   34.0  48.0  22.0  27.0  19.0  26.0  47.0  14.0  17.0  18.0  ...  20.0
6   36.0  39.0  29.0  31.0  32.0  33.0  38.0  26.0  28.0  25.0  ...  62.0
7   30.0  36.0  24.0  31.0  20.0  27.0  34.0  16.0  21.0  22.0  ...   7.0
8   15.0  26.0   9.0  12.0  10.0  14.0  23.0   3.0   6.0   5.0  ...  62.0
9   36.0  53.0  17.0  23.0  16.0  35.0  54.0   8.0  13.0  14.0  ...  56.0
10  43.0  58.0  17.0  22.0  24.0  44.0  56.0  16.0  27.0  22.0  ...  52.0

      60    61    62    63    64    65    66    67    68
0    3.0  30.0  10.0  43.0  63.0  61.0  65.0  64.0  66.0
1   55.0  41.0  37.0  52.0  57.0  66.0  56.0  59.0  65.0
2   43.0   4.0   3.0   7.0  53.0  65.0  60.0  64.0  66.0
3   59.0  56.0  40.0  51.0  44.0  65.0  61.0  43.0  66.0
4   49.0  26.0  28.0  29.0  52.0  56.0  55.0  64.0  65.0
5   37.0  10.0  15.0  11.0  49.0  54.0  51.0  52.0  53.0
6   68.0  61.0  60.0  59.0  58.0  57.0  56.0  55.0  69.0
7   13.0   5.0   6.0   8.0   4.0  14.0   2.0   1.0   3.0
8   68.0  60.0  59.0  58.0  57.0  56.0  55.0  67.0  69.0
9   58.0  46.0  48.0  47.0  66.0  67.0  65.0  69.0  68.0
10  59.0  47.0  48.0  46.0  65.0  67.0  66.0  68.0  69.0

[11 rows x 69 columns]

Transposed Ranks
       0     1     2     3     4     5     6     7     8     9     10
0   42.0  27.0  38.0   7.0  20.0  34.0  36.0  30.0  15.0  36.0  43.0
1   56.0  62.0  61.0  21.0  62.0  48.0  39.0  36.0  26.0  53.0  58.0
2   26.0  15.0  20.0   6.0  12.0  22.0  29.0  24.0   9.0  17.0  17.0
3   22.0  14.0  26.0   5.0  13.0  27.0  31.0  31.0  12.0  23.0  22.0
4   29.0  16.0  23.5   3.0  10.0  19.0  32.0  20.0  10.0  16.0  24.0
5   35.0  22.0  37.0   8.0  19.0  26.0  33.0  27.0  14.0  35.0  44.0
6   55.0  61.0  58.0  18.0  61.0  47.0  38.0  34.0  23.0  54.0  56.0
7   23.0  10.0  13.0   1.0   7.0  14.0  26.0  16.0   3.0   8.0  16.0
8   21.0  12.0  20.0   4.0  11.0  17.0  28.0  21.0   6.0  13.0  27.0
9   24.0  13.0  20.0   2.0   4.0  18.0  25.0  22.0   5.0  14.0  22.0
10  40.0  31.0  50.0  16.0  33.0  29.0  30.0  33.0  17.0  42.5  45.0
11  53.0  58.0  57.0  24.0  58.0  50.0  37.0  37.0  22.0  60.0  57.0
12  27.0  11.0  36.0  11.0  14.0  21.0  27.0  35.0  16.0  27.0   9.0
13  28.0  17.0  52.0  22.0  41.0  43.0  35.0  38.0  21.0  37.0  34.0
14  31.0  18.0  51.0  23.0  40.0  46.0  34.0  39.0  20.0  38.0  32.0
15  19.0   4.0   9.0  19.0   6.0   7.0   5.0  29.0  13.0  11.0   7.0
16   2.0   8.0  27.0   9.0  15.0   8.0   9.0  28.0  19.0  24.0  10.5
17  14.0   5.0   2.0  17.0   5.0   5.0   3.5  23.0   4.0   1.0   1.5
18   6.0   2.0  10.0  14.0   2.0   3.0   3.5  32.0   7.0   3.0   3.0
19  18.0   7.0   6.0  15.0   8.0   6.0   2.0  25.0   8.0   4.0   5.0
20  15.0   3.0   8.0  13.0   9.0   2.0   1.0  18.0  11.0   9.0   6.0
21   1.0   9.0  17.0  10.0  16.0   9.0   8.0  19.0  18.0  25.0  10.5
22   8.0   1.0   1.0  20.0   3.0   4.0   7.0  26.0   2.0   2.0   4.0
23   5.0   6.0   5.0  12.0   1.0   1.0   6.0  17.0   1.0   7.0   1.5
24  60.0  64.0  59.0  55.0  63.0  62.0  49.0  62.0  47.0  55.0  55.0
25  69.0  69.0  69.0  69.0  69.0  68.0  54.0  68.0  54.0  62.0  63.0
26  51.0  48.0  41.0  53.0  46.0  64.0  48.0  56.0  38.0  31.0  29.0
27  48.0  50.0  47.0  30.0  53.0  58.0  46.0  57.0  37.0  32.0  38.0
28  54.0  53.0  48.0  60.0  54.0  56.0  43.0  60.0  40.0  33.0  41.0
29  59.0  63.0  55.0  38.0  59.0  65.0  51.0  61.0  46.0  49.0  53.0
..   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
39  45.0  33.0  31.0  42.0  36.0  35.0  31.0  49.0  31.0  22.0  19.0
40  11.0  38.0  42.0  41.0  48.0  45.0  31.0  58.0  31.0  41.0  31.0
41  49.0  32.0  23.5  47.0  31.0  31.0  31.0  47.0  31.0  15.0  20.0
42  16.0  25.0  22.0  36.0  25.0  32.0  31.0  46.0  31.0  19.0  15.0
43  46.0  30.0  28.0  32.0  22.0  36.0  31.0  48.0  31.0  20.0  14.0
44  41.0  28.0  29.0  46.0  23.0  33.0  31.0  44.0  31.0  21.0  18.0
45  13.0  36.0  44.0  39.0  47.0  42.0  31.0  54.0  31.0  40.0  30.0
46  25.0  21.0  16.0  27.0  24.0  24.0  31.0  41.0  31.0   6.0  13.0
47  12.0  19.0  15.0  31.0  17.0  28.0  31.0  43.0  31.0  12.0   8.0
48  34.0  23.0  18.0  62.0  18.0  30.0  31.0  42.0  31.0  18.0  12.0
49  32.0  26.0  30.0  35.0  21.0  25.0  31.0  40.0  31.0  28.0  22.0
50  17.0  35.0  49.0  57.0  45.0  39.0  31.0  50.0  31.0  42.5  35.0
51  36.0  24.0  34.0  45.0  30.0  44.0  31.0  59.0  31.0   5.0  25.0
52   7.0  20.0  33.0  49.0  35.0  38.0  31.0  55.0  31.0  10.0  26.0
53  33.0  29.0  46.0  34.0  43.0  41.0  31.0  53.0  31.0  34.0  42.0
54  47.0  47.0  32.0  58.0  34.0  23.0  31.0  11.0  31.0  57.0  54.0
55   4.0  54.0  45.0  52.0  50.0  40.0  31.0  15.0  31.0  59.0  60.0
56  20.0  44.0  11.0  63.0  38.0  16.0  31.0   9.0  31.0  50.0  51.0
57   9.0  42.0  12.0  54.0  32.0  13.0  31.0  12.0  31.0  52.0  50.0
58  38.0  51.0  14.0  37.0  27.0  12.0  31.0  10.0  31.0  51.0  49.0
59  37.0  43.0  25.0  26.0  37.0  20.0  31.0   7.0  31.0  56.0  52.0
60   3.0  55.0  43.0  59.0  49.0  37.0  31.0  13.0  31.0  58.0  59.0
61  30.0  41.0   4.0  56.0  26.0  10.0  31.0   5.0  31.0  46.0  47.0
62  10.0  37.0   3.0  40.0  28.0  15.0  31.0   6.0  31.0  48.0  48.0
63  43.0  52.0   7.0  51.0  29.0  11.0  31.0   8.0  31.0  47.0  46.0
64  63.0  57.0  53.0  44.0  52.0  49.0  31.0   4.0  31.0  66.0  65.0
65  61.0  66.0  65.0  65.0  56.0  54.0  31.0  14.0  31.0  67.0  67.0
66  65.0  56.0  60.0  61.0  55.0  51.0  31.0   2.0  31.0  65.0  66.0
67  64.0  59.0  64.0  43.0  64.0  52.0  31.0   1.0  31.0  69.0  68.0
68  66.0  65.0  66.0  66.0  65.0  53.0  31.0   3.0  31.0  68.0  69.0

[69 rows x 11 columns]

IndexError: index 55 is out of bounds for axis 0 with size 45

<h3> Compute ranking scores for Configurations </h3>

In [298]:
import pandas as pd

df = pd.read_excel("C:\\Users\\Sadiq\\Desktop\\rankings.xlsx", header = None)
df = df.drop(0)
df = df.drop(0, axis = 1)
print("Rank Table \n", df.head(), "\n")

b=11         #total number of queries
t=45          #number of schemas
             #r is a rank number 1<=r<=t


# df_list = ["ST", "VT", "PT"]
print("Rank Scores \n")
for index, row in df.iterrows():
     
    s = 0
    for r in range(t):
        s = s + ( row[r+1]*(t-(r+1)) / (b*(t-1)) )
        
    print(index, "\t", s)

Rank Table
    1   2   3   4   5   6   7   8   9   10  ...  36  37  38  39  40  41  42  \
1   0   0   0   0   0   0   0   0   0   0  ...   2   1   1   0   0   0   0
2   0   0   0   0   0   0   0   0   0   0  ...   0   0   2   0   1   1   1
3   0   0   0   0   0   0   1   0   0   0  ...   0   0   0   0   0   0   0
4   0   0   0   0   0   1   0   0   0   0  ...   0   0   0   0   0   0   0
5   0   0   1   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0

   43  44  45
1   0   0   0
2   0   1   3
3   0   0   0
4   0   0   0
5   0   0   0

[5 rows x 45 columns]

Rank Scores

1 	 0.3409090909090909
2 	 0.11776859504132231
3 	 0.5371900826446281
4 	 0.4999999999999999
5 	 0.5413223140495868
6 	 0.3822314049586777
7 	 0.1446280991735537
8 	 0.6818181818181819
9 	 0.5909090909090909
10 	 0.6157024793388429
11 	 0.2644628099173554
12 	 0.12396694214876033
13 	 0.4545454545454546
14 	 0.2685950413223141
15 	 0.2644628099173554
16 	 0.6384297520661156
17 	 0.5743801652892562
18 	 0.7458677685950413
19 	 0.7561983471074379
20 	 0.6880165289256197
21 	 0.7107438016528925
22 	 0.6053719008264462
23 	 0.7644628099173554
24 	 0.8140495867768595
25 	 0.7768595041322315
26 	 0.6157024793388429
27 	 0.5847107438016528
28 	 0.5537190082644629
29 	 0.6074380165289257
30 	 0.45041322314049587
31 	 0.5681818181818182
32 	 0.4690082644628099
33 	 0.6301652892561983
34 	 0.6446280991735538
35 	 0.5805785123966942
36 	 0.5578512396694214
37 	 0.5206611570247933
38 	 0.6838842975206613
39 	 0.6880165289256198
40 	 0.5971074380165289
41 	 0.3016528925619835
42 	 0.25
43 	 0.2644628099173554
44 	 0.23760330578512395
45 	 0.23760330578512392